blueprint:
  name: Conditional Close Blinds
  description: Conditionally close blinds depending on if the window is open. When the window is open, allow cover to close half way, or stay open and automatically close once the window has shut.
  domain: automation
  source_url: https://github.com/cjmaio/ha-blueprints/blob/master/conditional-close-blinds.yaml
  input:
    cover:
      name: Cover
      selector:
        entity:
          domain: cover
    window_sensor:
      name: Window Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: window
    open_window_cover_close_pct:
      name: Open Window Cover Close Percentage
      default: 50
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider

variables:
  cover: !input cover
  open_window_cover_close_pct: !input open_window_cover_close_pct
  window_sensor: !input window_sensor

trigger:
  - platform: sun
    event: sunset
  - platform: state
    entity_id: !input window_sensor
    to: "off"

condition:
  - condition: sun
    before: sunrise
    after: sunset

action:
  - service: cover.set_cover_position
    target:
      entity_id: !input cover
    data_template:
      position: >
        {% if is_state(window_sensor, 'on') %} {{open_window_cover_close_pct}} {% else %} 0 {% endif %}
  - delay:
      seconds: 20
  - service: cover.set_cover_position
    target:
      entity_id: !input cover
    data_template:
      position: >
        {% if is_state(window_sensor, 'on') -%} {{open_window_cover_close_pct}} {%- else -%} 0 {%- endif %}
